[build]
  command = "pnpm run build"

[build.environment]
  # Allow Netlify CI to install even if pnpm-lock.yaml is out of date
  PNPM_CONFIG_FROZEN_LOCKFILE = "false"
  # Alternatively, you can use PNPM_FLAGS instead of PNPM_CONFIG_FROZEN_LOCKFILE
  # PNPM_FLAGS = "--no-frozen-lockfile"


